### ISSUE TITLE
Update to API v2.

### ISSUE THREAD

**Issue by v0dro** [dennmart/wanikani-gem#2]
The current API will be deprecated soon. Would be great to update to the latest API.

**Comment by Dahie** [comment]
Hi, I'm looking into upgrading the gem to v2. The new API is very different to the old one and it looks like it's hard to keep the same gem API as with v1. Do people have thoughts about keeping rough compatibility to the old API or is it ok to come up with a new interface that better reflects the features Wanikani's API offers?

// @dennmart

**Comment by v0dro** [comment]
I'd be fine with a new interface. The one you propose is also more ruby-like so would be great to have :)

Also, it would be great if we could have a feature to show stats of the most recent reviews and download the vocab/kanji that went wrong for that particular review.

**Comment by Dahie** [comment]
I have a rough update at https://github.com/Dahie/wanikani-gem/tree/api-version-2 for playing. The documentation is not updated yet and this contains code for both APIs V1 and V2. Given that V1 is removed in September, I'd suggest to make this a version 3.0 of the wanikani-gem and remove all API-v1 code, but that's a decision for @dennmart. I'm happy to provide whatever direction is requested to merge my code into this gem. I'm not interested in maintaining a fork. :)

**Comment by Dahie** [comment]
Hi @dennmart, do you have input about the future of the gem? :)

**Comment by dennmart** [comment]
@Dahie Sorry I hadn't responded to this earlier!

Thanks for taking the lead on making the changes for supporting the new version of the API. I haven't been paying much attention to WaniKani's API changes and didn't know version 1.x would be shut down in a couple of months.

I agree with what you mentioned. My inclination would be to have version 3.0 of the gem use API v2 only instead of having the option to use either version of the API as you have in your fork. That way there's no mix-up in supporting both for just a couple of months. If someone would need to use this gem to access the old API while it still exists, they can always grab an older version of the gem.

If you can submit any code to help me move that direction, it's always appreciated! I'll try to dedicate some time this week to dive into the new API endpoints for WaniKani and see what's new and what needs to change in the gem. Then I'll make a list of what updates to make for getting an update out sooner rather than later. I'll keep everyone posted in this issue.

**Comment by Dahie** [comment]
Awesome! I support this choice! I'll prepare a pull-request with my proposal of gem v3 in the next couple of days.

**Comment by Dahie** [comment]
Any updates on the reviews of #3 and #4 (a proposal for gem version 2 to deprecate methods.)

@dennmart Anything more you'd like to see?

**Comment by Dahie** [comment]
@dennmart any updates? The old API will be shutdown in a month

**Comment by dennmart** [comment]
I've already apologized elsewhere but I need to do it again - I really am sorry for dropping the ball on this for so long.

The good news is that version 3.0.0 of the gem is now live and working with WaniKani API v2. Huge thanks to @Dahie for taking the time to update the gem in #3. I'll make sure to pay closer attention to the API changes so I don't let future changes pass by like this again.
